=== JoyM268/sdmcet-web/Unit - 1/XML/StudentInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"></xs:element>
              <xs:element name="usn" type="xs:string"></xs:element>
              <xs:element name="branch" type="xs:string"></xs:element>
              <xs:element name="semester" type="xs:string"></xs:element>
              <xs:element name="cgpa" type="xs:decimal"></xs:element>
            </xs:sequence>
            <xs:attribute name="rollno" type="xs:integer" use="required"></xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JoyM268/sdmcet-web/Unit - 1/XML/StudentInfo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Student Details, validation using XSD -->
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="StudentInfo.xsd">
  <student rollno="111">
    <name>Mohan M</name>
    <usn>2SD12CS020</usn>
    <branch>CSE</branch>
    <semester>3</semester>
    <cgpa>6.98</cgpa>
  </student>
  
  <student rollno="222">
    <name>Vikas V</name>
    <usn>2SD12CS018</usn>
    <branch>CSE</branch>
    <semester>3</semester>
    <cgpa>9.98</cgpa>
  </student>

  <student rollno="333">
    <name>Murli M</name>
    <usn>2SD12CS080</usn>
    <branch>CSE</branch>
    <semester>3</semester>
    <cgpa>8.98</cgpa>
  </student>
</Students>
