=== JoyM268/sdmcet-web/XML/orders.dtd
<!ELEMENT orders (order+)>
<!ELEMENT order (name,item,qty,price,address)>
<!ATTLIST order id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT qty (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT address (city,state,country)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>

=== JoyM268/sdmcet-web/XML/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orders SYSTEM "orders.dtd">
<orders>
    <order id="O111">
        <name>Mohan</name>
        <item>LED TV</item>
        <qty>1</qty>
        <price>150000</price>
        <address>
            <city>Dharwad</city>
            <state>Karnataka</state>
            <country>India</country>
        </address>
    </order>

    <order id="O555">
        <name>Vikas</name>
        <item>Speakers</item>
        <qty>1</qty>
        <price>1500</price>
        <address>
            <city>Dharwad</city>
            <state>Karnataka</state>
            <country>India</country>
        </address>
    </order>
</orders>
