=== JoyM268/sdmcet-web/XML/SDMInfo.dtd
<!ELEMENT sdmcet (branch)>
<!ELEMENT branch (cse,ise,ec,mech,civil,chemical)>
<!ELEMENT cse (ug,ugintake,rpgintake,pg)>
<!ATTLIST cse id CDATA #REQUIRED>
<!ELEMENT ug (#PCDATA)>
<!ELEMENT ugintake (#PCDATA)>
<!ELEMENT rpgintake (#PCDATA)>
<!ELEMENT pg (#PCDATA)>
<!ELEMENT ise (ug,ugintake)>
<!ATTLIST ise id NMTOKEN #REQUIRED>
<!ELEMENT ec (ugintake,pgintake,ug,pg)>
<!ATTLIST ec id NMTOKEN #REQUIRED>
<!ELEMENT pgintake (#PCDATA)>
<!ELEMENT mech (ugintake,pgintake,ug,pg)>
<!ATTLIST mech id NMTOKEN #REQUIRED>
<!ELEMENT civil (ugintake,pgintake,ug,pg)>
<!ATTLIST civil id NMTOKEN #REQUIRED>
<!ELEMENT chemical (ugintake,ug)>
<!ATTLIST chemical id NMTOKEN #REQUIRED>

=== JoyM268/sdmcet-web/XML/SDMInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Branch Details -->
<!DOCTYPE sdmcet SYSTEM "SDMInfo.dtd">
<sdmcet>
    <branch>
        <cse id="1">
            <ug>BE</ug>
            <ugintake>150</ugintake>
            <rpgintake>18</rpgintake>
            <pg>MTech</pg>
        </cse>
        <ise id="2">
            <ug>BE</ug>
            <ugintake>150</ugintake>
        </ise>
        <ec id="3">
            <ugintake>150</ugintake>
            <pgintake>18</pgintake>
            <ug>BE</ug>
            <pg>MTech</pg>
        </ec>
        <mech id="4">
            <ugintake>150</ugintake>
            <pgintake>18</pgintake>
            <ug>BE</ug>
            <pg>MTech</pg>
        </mech>
        <civil id="5">
            <ugintake>60</ugintake>
            <pgintake>18</pgintake>
            <ug>BE</ug>
            <pg>MTech</pg>
        </civil>
        <chemical id="6">
            <ugintake>60</ugintake>
            <ug>BE</ug>
        </chemical>
    </branch>
</sdmcet>
