=== JoyM268/sdmcet-web/XML/StudentInfo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Students (student+)>
<!ELEMENT student (name,usn,branch,semester,cgpa)>
<!ATTLIST student rollno CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT usn (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT cgpa (#PCDATA)>

=== JoyM268/sdmcet-web/XML/StudentInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Student Details -->
<!DOCTYPE Students SYSTEM "StudentInfo.dtd">
<Students>
  <student rollno="111">
    <name>Mohan M</name>
    <usn>2SD12CS020</usn>
    <branch>CSE</branch>
    <semester>3</semester>
    <cgpa>6.98</cgpa>
  </student>
  
  <student rollno="112">
    <name>Murli M</name>
    <usn>2SD12CS080</usn>
    <branch>CSE</branch>
    <semester>3</semester>
    <cgpa>8.98</cgpa>
  </student>
</Students>
